train: false
work_dir: ""
seed: 234
use_wandb: false

# TRAINING
num_workers: 1
batch_size: 8


# EXPERIMENT
use_final_ckpt: false
finetune: false
ckpt_dir: ???

# TRANSFER TEST
transfer:
  enabled: false
  out_dir: ${work_dir}/transfer_outputs


defaults:
  - task: ???
  - dataset: ???
  - encoder: ???
  - decoder: ???
  - preprocessing: ???
  - criterion: ???
  - lr_scheduler: multi_step_lr
  - optimizer: adamw
  - _self_ 